trigger: none
pr: none

pool:
  vmImage: windows-2019

# parameters:
# - name: version
#   displayName: Version

# - name: test
#   default: test

variables:


resources:
  pipelines:
  - pipeline: test
    source: test
    branch: 'refs/tags/${{ variables.test }}'

jobs:
  - job: TestJob
    displayName: Test Job
    steps:
    # - download: test

    # - pwsh: |
    #     Get-ChildItem -Recurse
    #   workingDirectory: $(Pipeline.Workspace)/test/base-dev
    #   displayName: pwsh ${{ parameters.test }}

    - pwsh: |
        Write-Host $(Build.SourceBranch)