trigger: none
pr: none

pool:
  vmImage: windows-2019

parameters:
- name: version
- name: branch

jobs:
  - job: TestJob
    displayName: Test Job
    steps:

    # - task: DownloadPipelineArtifact@2
    #   inputs:
    #     source: specific
    #     project: $(system.teamProject)
    #     pipeline: 40
    #     runVersion: latestFromBranch
    #     runBranch: ${{ parameters.branch }}
    #     tags: ${{ parameters.version }}
    #     artifacts: base-dev

      - task: DownloadPipelineArtifact@2
        inputs:
          source: specific
          project: $(system.teamProject)
          pipeline: 40
          runVersion: latestFromBranch
          runBranch: ${{ parameters.branch }}
          tags: ${{ parameters.version }}
          artifact: "base-dev"
          path: "$(Pipeline.Workspace)/base-dev"

    # - pwsh: |
    #     Get-ChildItem -Recurse
    #   workingDirectory: $(Pipeline.Workspace)/base-dev
    #   displayName: test