trigger: none
pr: none

pool:
  vmImage: windows-2019

parameters:
- name: version
  displayName: Version

resources:
  pipelines:
  - pipeline: test
    source: test
    branch: refs/tags/{{ parameters.version }}

jobs:
  - job: TestJob
    displayName: Test Job
    steps:
    - download: test

    - pwsh: |
        Get-ChildItem -Recurse
      workingDirectory: $(Pipeline.Workspace)/test/base-dev
      displayName: pwsh test