trigger: none
pr: none

pool:
  vmImage: windows-2019

parameters:
- name: version

jobs:
  - job: TestJob
    displayName: Test Job
    steps:

    - pwsh: |
        Write-Host "refs/tags/${{ parameters.version }}"
      displayName: test

    - task: DownloadPipelineArtifact@2
      inputs:
        source: specific
        project: DevOps
        pipeline: 40
        runVersion: latestFromBranch
        runBranch: refs/tags/${{ parameters.version }}
        tags: ${{ parameters.version }}

    - pwsh: |
        Get-ChildItem -Recurse
      workingDirectory: $(Pipeline.Workspace)/base-dev
      displayName: test