trigger: none
pr: none

pool:
  vmImage: ${{ parameters.agent }}

parameters:
- name: version
  displayName: Version

- name: agent
  default: windows-2019

resources:
  pipelines:
  - pipeline: test
    source: test
    branch: refs/tags/v1.3.4
    # branch: refs/tags/${{ parameters.version }}

jobs:
  - job: TestJob
    displayName: Test Job
    steps:
    - download: test

    - pwsh: |
        Get-ChildItem -Recurse
      workingDirectory: $(Pipeline.Workspace)/test/base-dev
      displayName: pwsh test