trigger: none
pr: none

pool:
  vmImage: windows-2019

parameters:
- name: test
  default: refs/tags/v1.3.7

# resources:
#   pipelines:
#   - pipeline: test
#     source: test
#     branch: ${{ parameters.test }}

jobs:
  - job: TestJob
    displayName: Test Job
    steps:
    # - download: test

    # - pwsh: |
    #     Get-ChildItem -Recurse
    #   workingDirectory: $(Pipeline.Workspace)/test/base-dev
    #   displayName: pwsh ${{ parameters.test }}

    - pwsh: |
        Write-Host $(Build.SourceBranch)

    # - task: DownloadPipelineArtifact@2
    #   displayName: Download Pipeline Artifact
    #   inputs:
    #     buildType: specific
    #     project: ca2d4974-8a7b-4718-b139-e12329227f31
    #     definition: 40
    #     tags: v1.3.7
    #     artifactName: base-dev

    - task: DownloadPipelineArtifact@2
      inputs:
        source: specific
        project: DevOps
        pipeline: 40
        runVersion: latestFromBranch
        runBranch: refs/heads/develop
        tags: 757