trigger: none
pr: none

pool:
  vmImage: windows-2019

parameters:
- name: test
  default: refs/tags/v1.3.7

jobs:
  - job: TestJob
    displayName: Test Job
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        source: specific
        project: DevOps
        pipeline: 40
        runVersion: latestFromBranch
        runBranch: refs/heads/develop
        tags: blah

    # - pwsh: |
    #     Get-ChildItem -Recurse
    #   workingDirectory: $(Pipeline.Workspace)/test/base-dev
    #   displayName: test

    - pwsh: |
        Get-ChildItem -Recurse
      workingDirectory: $(Pipeline.Workspace)/base-dev
      displayName: test