trigger: none
pr: none

pool:
  vmImage: windows-2019

parameters:
- name: test
  default: refs/tags/v1.3.7

# resources:
#   pipelines:
#   - pipeline: test
#     source: test
#     branch: ${{ parameters.test }}

jobs:
  - job: TestJob
    displayName: Test Job
    steps:
    # - download: test

    - task: DownloadPipelineArtifact@2
      inputs:
        source: specific
        project: DevOps
        pipeline: 40
        runVersion: latestFromBranch
        runBranch: refs/heads/develop
        tags: blah

    # - pwsh: |
    #     Get-ChildItem -Recurse
    #   workingDirectory: $(Pipeline.Workspace)/test/base-dev
    #   displayName: test

    - pwsh: |
        Get-ChildItem -Recurse
      workingDirectory: $(Pipeline.Workspace)
      displayName: test