parameters:
- name: global_product_version
  displayName: Product Version

variables:
- name: global_product_version
  value: ${{ parameters.global_product_version }}

stages:
  - stage: Test
    displayName: Test
    dependsOn: []
    pool:
      vmImage: ubuntu-22.04
    jobs:
    - job: Test
      steps:
      - checkout: none

      - pwsh: |
          Write-Host "Test"

      - pwsh: |
          write-host "##vso[task.setvariable variable=version;isOutput=true]$(global_product_version)"
        displayName: Tattoo
        name: Tattoo

  - stage: After
    condition: eq(variables.version, 'true')
    displayName: After
    dependsOn:
     - Test
    pool:
      vmImage: ubuntu-22.04
    variables:
      version: $[stageDependencies.Test.Test.outputs['Tattoo.version']]
    jobs:
    - job: After
      steps:
      - checkout: none

      - pwsh: |
          Write-Host "$(version)"