trigger:
- none

parameters:
- name: agent
  displayName: Agent
  values:
    - windows-2019
    - ubuntu-20.04
  default: windows-2019

- name: foo
  displayName: Agent
  default: bar

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: Uno
    pool:
      vmImage: ${{ parameters.agent }}
    jobs:
    - job: test
      steps:
      - task: KubectlInstaller@0
        displayName: 'Install Kubectl latest'

  - stage: Due
    jobs:
    - job: DeployDue
      steps:
      - template: templates/template.yaml

  - stage: Quatro
    dependsOn:
      - Uno
      - Due
    jobs:
    - job: test
      steps:
      - task: Bash@3
        displayName: 'Bash Something'
        inputs:
          targetType: 'inline'
          script: |
            echo doing something


## Stages with deployment jobs
# stages:
#   - stage: Deploy_Test_1
#     jobs:
#     - deployment: test
#       environment: test
#       strategy:
#         runOnce:
#           deploy:
#             steps:
#             - task: KubectlInstaller@0
#               displayName: 'Install Kubectl latest'
#             - task: Bash@3
#               displayName: 'Bash Something'
#               inputs:
#                 targetType: 'inline'
#                 script: |
#                   sleep 15s
#                   echo gotovo spavanje

#   - stage: Deploy_Test_2
#     jobs:
#     - deployment: test
#       environment: test
#       strategy:
#         runOnce:
#           deploy:
#             steps:
#             - task: Bash@3
#               displayName: 'Bash Something'
#               inputs:
#                 targetType: 'inline'
#                 script: |
#                   echo doing something 2