trigger: none
pr: none

# pool:
#   vmImage: ubuntu-20.04

stages:
  - stage: Build
    jobs:
    - template: templates/build-sample-job.yaml

    - job: TestJob
      pool:
        vmImage: windows-2019
      displayName: Test Job
      steps:
      - pwsh: |
          Write-Host "##vso[task.setvariable variable=foo;isOutput=true]barrrr"
        displayName: foooo
        name: foooo

      - pwsh: |
          Write-Host "$(foooo.foo)"
        displayName: Test print

    - job: TestJob2
      pool:
        vmImage: ubuntu-20.04
      displayName: Test Job2
      dependsOn:
        - TestJob
      variables:
        varFoo: $[ dependencies.TestJob.outputs['foooo.foo'] ]
      steps:
      - pwsh: |
          Write-Host "$(varFoo)"
        displayName: Test print