trigger: none
pr: none

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: Build
    jobs:
    - template: templates/build-sample-job.yaml

    - job: TestJob
      displayName: Test Job
      steps:
        - pwsh: |
            Write-Host "##vso[task.setvariable variable=$foo]barrrr"

        - pwsh: |
            Write-Host "$(foo)"

    - job: TestJob2
      displayName: Test Job2
      dependsOn:
        - TestJob
      steps:
        - pwsh: |
            Write-Host "$(foo)"