trigger:
- none

parameters:
- name: agent
  displayName: Agent
  values:
    - windows-2019
    - ubuntu-20.04
  default: windows-2019

- name: foo
  displayName: test
  default: bar

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: Uno
    pool:
      vmImage: ${{ parameters.agent }}
    dependsOn: []
    jobs:
    - job: test
      steps:
      - ${{ each parameter in parameters }}:
        - powershell: |
            Write-Host "##vso[task.setvariable variable=${{ parameter.key }}]${{ parameter.value}}"
          displayName: Expand ${{ parameter.key }}
      - pwsh: |
          Write-Host "$(foo)"

      - task: KubectlInstaller@0
        displayName: 'Install Kubectl latest'

  - stage: Due
    dependsOn: []
    jobs:
    - job: DeployDue
      steps:
      - ${{ each parameter in parameters }}:
        - powershell: |
            Write-Host "##vso[task.setvariable variable=${{ parameter.key }}]${{ parameter.value}}"
          displayName: Expand ${{ parameter.key }}

      - template: templates/template.yaml

  - stage: Quatro
    dependsOn:
      - Uno
      - Due
    jobs:
    - job: test
      steps:
      - task: Bash@3
        displayName: 'Bash Something'
        inputs:
          targetType: 'inline'
          script: |
            echo doing something