trigger: none
pr: none

parameters:
- name: global_product_version
  displayName: Product Version

variables:
- name: version
  value: ${{ parameters.global_product_version }}

stages:
  - stage: Test
    displayName: Test
    dependsOn: []
    pool:
      vmImage: ubuntu-22.04
    jobs:
    - job: Test
      steps:
      - checkout: none

      - pwsh: |
          Write-Host "$(global_product_version)"

      - pwsh: |
          if ("$(global_product_version)" -match "^(\d+\.)?(\d+\.)?(\*|\d+)$") {
            write-host "ide"
          } else {
            write-host "ne ide"
          }
        displayName: test
        name: test

      - pwsh: |
          if ("$(global_product_version)" -match "^(\d+\.)?(\d+\.)?(\*|\d+)$") {
            write-host "##vso[task.setvariable variable=release;]yes"
          } else {
            write-host "##vso[task.setvariable variable=release;]no"
          }
        displayName: Tattoo
        name: Tattoo

      - pwsh: |
          Write-Host "$(foo)"
        displayName: foo
        condition: eq(variables.foo, 'yes')