trigger: none
pr: none

parameters:
- name: global_product_version
  displayName: Product Version

stages:
  - stage: Test
    displayName: Test
    dependsOn: []
    pool:
      vmImage: ubuntu-22.04
    jobs:
    - job: Test
      steps:
      - checkout: none

      - pwsh: |
          Write-Host "${{ parameters.global_product_version }}"

      - pwsh: |
          if (${{ parameters.global_product_version }} -match "^(\d+\.)?(\d+\.)?(\*|\d+)$") {
            write-host "ide"
          } else {
            write-host "ne ide"
          }
        displayName: test
        name: test

      - pwsh: |
          if (${{ parameters.global_product_version }} -match "^(\d+\.)?(\d+\.)?(\*|\d+)$") {
            write-host "##vso[task.setvariable variable=release;isOutput=true]true"
          } else {
            write-host "##vso[task.setvariable variable=release;isOutput=true]false"
          }
        displayName: Tattoo
        name: Tattoo

  - stage: After
    condition: eq(variables.release, 'true')
    displayName: After
    dependsOn:
     - Test
    pool:
      vmImage: ubuntu-22.04
    variables:
      version: $[stageDependencies.Test.Test.outputs['Tattoo.version']]
    jobs:
    - job: After
      steps:
      - checkout: none

      - pwsh: |
          Write-Host "$(release)"