parameters:
- name: global_product_version
  displayName: Product Version

variables:
- name: global_product_version
  value: ${{ parameters.global_product_version }}

stages:
  - stage: Test
    displayName: Test
    dependsOn: []
    pool:
      vmImage: ubuntu-22.04
    jobs:
    - job: Test
      steps:
      - checkout: none

      - pwsh: |
          Write-Host "$(global_product_version)"

      - pwsh: |
          if ($(global_product_version) -match "^\d+(?:\.\d+){2}$") {
            write-host "ide"
          } else {
            write-host "ne ide"
          }
        displayName: test
        name: test

      - pwsh: |
          if ($(global_product_version) -match "^\d+(?:\.\d+){2}$") {
            write-host "##vso[task.setvariable variable=release;isOutput=true]true"
          } else {
            write-host "##vso[task.setvariable variable=release;isOutput=true]false"
          }
        displayName: Tattoo
        name: Tattoo

  - stage: After
    condition: eq(variables.release, 'true')
    displayName: After
    dependsOn:
     - Test
    pool:
      vmImage: ubuntu-22.04
    variables:
      version: $[stageDependencies.Test.Test.outputs['Tattoo.version']]
    jobs:
    - job: After
      steps:
      - checkout: none

      - pwsh: |
          Write-Host "$(release)"
          Write-Host "$(global_product_version)"