parameters:
- name: global_product_version
  displayName: Product Version

variables:
- name: foo
  value: bar

stages:
  - stage: Test
    displayName: Test
    dependsOn: []
    pool:
      vmImage: ubuntu-22.04
    jobs:
    - job: Test
      steps:
      - checkout: none

      - pwsh: |
          Write-Host "Test"

  - stage: After
    displayName: After
    dependsOn:
     - Test
    pool:
      vmImage: ubuntu-22.04
    jobs:
    - job: After
      steps:
      - checkout: none

      - pwsh: |
          Write-Host "After"