trigger: none
pr: none

parameters:
- name: global_product_version
  displayName: Product Version

variables:
- name: version
  value: ${{ parameters.global_product_version }}

stages:
  - stage: Test
    displayName: Test
    dependsOn: []
    pool:
      vmImage: ubuntu-22.04
    jobs:
    - job: Test
      steps:
      - checkout: none

      - pwsh: |
          Write-Host "$(version)"

      - pwsh: |
          if ("$(version)" -match "^(\d+\.)?(\d+\.)?(\*|\d+)$") {
            write-host "ide"
          } else {
            write-host "ne ide"
          }
        displayName: test
        name: test

      - pwsh: |
          if ("$(version)" -match "^(\d+\.)?(\d+\.)?(\*|\d+)$") {
            write-host "##vso[task.setvariable variable=release;isOutput=true]yes"
            write-host "##vso[task.setvariable variable=foo;]yes"
          } else {
            write-host "##vso[task.setvariable variable=release;isOutput=true]no"
            write-host "##vso[task.setvariable variable=foo;]no"
          }
        displayName: Tattoo
        name: Tattoo

      - pwsh: |
          Write-Host "$(foo)"
        displayName: foo

  - stage: After
    condition: eq(variables.rc, 'yes')
    displayName: After
    dependsOn:
     - Test
    pool:
      vmImage: ubuntu-22.04
    variables:
      rc: $[stageDependencies.Test.Test.outputs['Tattoo.release']]
    jobs:
    - job: After
      steps:
      - checkout: none

      - pwsh: |
          Write-Host "$(rc)"