trigger:
  batch: true
  paths:
    include:
      - a
pr:
  autoCancel: false
  branches:
    include:
      - develop
  paths:
    include:
      - a

variables:
  vmImage: ubuntu-20.04

jobs:

- job: BuildAndTest
  pool:
    vmImage: $(vmImage)
  steps:
    - pwsh: |
        Start-Sleep 20
        Write-Host "A CI"