# #https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops&WT.mc_id=AZ-MVP-5003246&WT.mc_id=AZ-MVP-5003246#create-and-build-the-dockerfile-1

FROM ubuntu:20.04

# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    git \
    iputils-ping \
    libcurl4 \
    libunwind8 \
    netcat \
    libssl1.0 \
  && rm -rf /var/lib/apt/lists/*

RUN curl -LO https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl \
    chmod +x ./kubectl \
    mv ./kubectl /usr/local/bin/kubectl

# RUN curl -LO https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl \
#     install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# RUN curl -LsS https://aka.ms/InstallAzureCLIDeb | bash \
#   && rm -rf /var/lib/apt/lists/*

# RUN kubectl version --client

ARG TARGETARCH=amd64
ARG AGENT_VERSION=2.194.0

WORKDIR /azp
RUN if [ "$TARGETARCH" = "amd64" ]; then \
      AZP_AGENTPACKAGE_URL=https://vstsagentpackage.azureedge.net/agent/${AGENT_VERSION}/vsts-agent-linux-x64-${AGENT_VERSION}.tar.gz; \
    else \
      AZP_AGENTPACKAGE_URL=https://vstsagentpackage.azureedge.net/agent/${AGENT_VERSION}/vsts-agent-linux-${TARGETARCH}-${AGENT_VERSION}.tar.gz; \
    fi; \
    curl -LsS "$AZP_AGENTPACKAGE_URL" | tar -xz

COPY agent/ubuntu/start.sh .
RUN chmod +x start.sh

ENTRYPOINT [ "./start.sh" ]