trigger: none
pr: none

pool:
  vmImage: ubuntu-20.04

# variables:
# - name: container_registry
#   value: alsidforad
# - name: DOCKER_BUILDKIT
#   value: 1

# jobs:
# - job: UbuntuAgent
#   steps:
#   - task: Docker@2
#     displayName: Build Ubuntu Agent
#     inputs:
#       containerRegistry: $(container_registry)
#       repository: agent-ubuntu
#       command: build
#       Dockerfile: agent/ubuntu/Dockerfile
#       buildContext: '.'
#       arguments: ''
#       tags: |
#         test

#   - task: Docker@2
#     displayName: Push Ubuntu Agent
#     inputs:
#       containerRegistry: $(container_registry)
#       repository: agent-ubuntu
#       command: push
#       tags: |
#         test
parameters:
- name: foo
  default: bar

steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: Replace tokens in Ansible files
  inputs:
    # rootDirectory: $(Pipeline.Workspace)/ansible
    targetFiles: |
      a.ps1
      a_${{ parameters.foo }}
    tokenPrefix: '<-'
    tokenSuffix: '->'

      # "host_${{ parameters.role }}"
      # all_vm_falcon_agent.yaml