trigger:
  paths:
    include:
      - service
pr:
  autoCancel: false
  branches:
    include:
      - develop
  paths:
    include:
      - service

variables:
  vmImage: ubuntu-20.04

jobs:

- job: BuildAndTest
  pool:
    vmImage: $(vmImage)
  steps:
    - pwsh: |
        Write-Host "A CI" 