trigger:
  batch: true
  paths:
    include:
      - service
pr:
  autoCancel: true
  branches:
    include:
      - develop
  paths:
    include:
      - service

variables:
  vmImage: ubuntu-20.04

jobs:

- job: BuildAndTest
  pool:
    vmImage: $(vmImage)
  steps:
    - pwsh: |
        Start-Sleep 10
        Write-Host "Do some CI" 