trigger:
- none

pool:
  vmImage: ubuntu-20.04

# resources:
#   xxx

variables:
 foo: "bar"

stages:
  - stage: Uno
    jobs:
    - job: test
      steps:
      - task: KubectlInstaller@0
        displayName: 'Install Kubectl latest'

  - stage: Due
    dependsOn: Uno
    jobs:
    - job: test
      steps:
      - task: Bash@3
        displayName: 'Bash Something'
        inputs:
          targetType: 'inline'
          script: |
            echo doing something

  - stage: Tre
    dependsOn: Uno
    jobs:
    - job: test
      steps:
      - task: Bash@3
        displayName: 'Bash Something'
        inputs:
          targetType: 'inline'
          script: |
            echo doing something

  - stage: Quatro
    dependsOn: ['Due','Tre']
    jobs:
    - job: test
      steps:
      - task: Bash@3
        displayName: 'Bash Something'
        inputs:
          targetType: 'inline'
          script: |
            echo doing something