trigger:
- none

pool:
  vmImage: ubuntu-20.04

# resources:
#   xxx

variables:
 foo: "bar"

# stages:
#   - stage: Uno
#     jobs:
#     - job: test
#       steps:
#       - task: KubectlInstaller@0
#         displayName: 'Install Kubectl latest'

#   - stage: Due
#     dependsOn: Uno
#     jobs:
#     - job: test
#       steps:
#       - task: Bash@3
#         displayName: 'Bash Something'
#         inputs:
#           targetType: 'inline'
#           script: |
#             echo doing something

#   - stage: Tre
#     dependsOn: Uno
#     jobs:
#     - job: test
#       steps:
#       - task: Bash@3
#         displayName: 'Bash Something'
#         inputs:
#           targetType: 'inline'
#           script: |
#             echo doing something

#   - stage: Quatro
#     dependsOn:
#       - Due
#       - Tre
#     jobs:
#     - job: test
#       steps:
#       - task: Bash@3
#         displayName: 'Bash Something'
#         inputs:
#           targetType: 'inline'
#           script: |
#             echo doing something


# stages:
#   - stage: Deploy_Test_1
#     jobs:
#     - deployment: test
#       environment: test
#       strategy:
#         runOnce:
#           deploy:
#             steps:
#             - task: KubectlInstaller@0
#               displayName: 'Install Kubectl latest'
#             - task: Bash@3
#               displayName: 'Bash Something'
#               inputs:
#                 targetType: 'inline'
#                 script: |
#                   echo doing something

#   - stage: Deploy_Test_2
#     jobs:
#     - deployment: test
#       environment: test
#       strategy:
#         runOnce:
#           deploy:
#             steps:
#             - task: Bash@3
#               displayName: 'Bash Something'
#               inputs:
#                 targetType: 'inline'
#                 script: |
#                   echo doing something 2

strategy:
  matrix:
    ubuntu14:
      containerImage: ubuntu:14.04
    ubuntu16:
      containerImage: ubuntu:16.04
    ubuntu18:
      containerImage: ubuntu:18.04

container: $[ variables['containerImage'] ]

steps:
- script: printenv