trigger:
- none

pool:
  vmImage: ubuntu:20-04

# resources:
#   xxx

variables:
 foo: "bar"

- stages: Uno
  jobs:
  - job: test
    steps:
    - task: KubectlInstaller@0
      displayName: 'Install Kubectl latest'

- stages: Due
  jobs:
  - job: test
    steps:
    - task: Bash@3
      displayName: 'Bash Something'
      inputs:
        targetType: 'inline'
        script: |
          echo doing something