parameters:
- name: test

jobs:
- job: DeployDlVm
  pool:
    vmImage: ubuntu-20.04
  displayName: Deploy DL VM
  steps:
  - pwsh: |
      Write-Host "${{ parameters.test }} the template job"

  - pwsh: |
          Write-Host "$(marta)"
# parameters:
#   - name: preBuild
#     type: stepList
#     default: []
#   - name: postBuild
#     type: stepList
#     default: []
  
# jobs:
# - job:
#   displayName: Build Project
#   steps:
    
#     - task: Bash@3
#       displayName: 'Restore'
#       inputs:
#         targetType: 'inline'
#         script: |
#           echo Restoring
     
#     - ${{ parameters.preBuild }}

#     - task: Bash@3
#       displayName: 'Build'
#       inputs:
#         targetType: 'inline'
#         script: |
#           echo Building
          
#     - ${{ parameters.postBuild }}

#     - task: Bash@3
#       displayName: 'Publish'
#       inputs:
#         targetType: 'inline'
#         script: |
#           echo Publishing