# trigger:
#   branches:
#     include:
#       - refs/tags/v*

# pr: none

# name: $(BuildID)

# pool:
#   vmImage: ubuntu-latest
#   # vmImage: windows-2019

# stages:
#   - stage: Stage1
#     dependsOn: []
#     # pool:
#     #   vmImage: ubuntu-latest
#     jobs:
#     - job: Stage1
#       steps:
#       - pwsh: |
#           Write-Host "Stage11"

#       - template: ../templates/template.yaml

#   - stage: Stage2
#     dependsOn: []
#     # pool:
#     #   vmImage: ubuntu-latest
#     jobs:
#     - job: Stage2
#       steps:
#       - pwsh: |
#           Write-Host "Stage2"

#       - template: ../templates/template.yaml

trigger: none
pr: none

parameters:
- name: global_architecture
  displayName: Architecture
  values:
    - SaaS with VPN
    - SaaS with TLS
    - Lab

pool:
  vmImage: windows-2019

variables:
  architecture: {{ parameters.architecture }}

stages:
  - stage: Stage1
    dependsOn: []
    jobs:
    - job: Stage1
      steps:
      - pwsh: |
          Write-Host "Stage11"

  - stage: Stage2
    dependsOn:
      - Stage1
    jobs:
    - job: Stage2
      steps:
      - pwsh: |
          Write-Host "Stage2"

  - stage: Stage3
    # dependsOn:
    #   - Stage2
    condition: and(succeeded(), eq(variables.architecture, 'Lab'))
    jobs:
    - job: Stage3
      steps:
      - pwsh: |
          Write-Host "Stage3"