# trigger:
#   branches:
#     include:
#       - refs/tags/v*

# pr: none

# name: $(BuildID)

# pool:
#   vmImage: ubuntu-latest
#   # vmImage: windows-2019

# stages:
#   - stage: Stage1
#     dependsOn: []
#     # pool:
#     #   vmImage: ubuntu-latest
#     jobs:
#     - job: Stage1
#       steps:
#       - pwsh: |
#           Write-Host "Stage11"

#       - template: ../templates/template.yaml

#   - stage: Stage2
#     dependsOn: []
#     # pool:
#     #   vmImage: ubuntu-latest
#     jobs:
#     - job: Stage2
#       steps:
#       - pwsh: |
#           Write-Host "Stage2"

#       - template: ../templates/template.yaml

trigger: none
pr: none

pool:
  vmImage: windows-2019

parameters:
- name: global_architecture
  displayName: Architecture
  values:
    - SaaS with VPN
    - SaaS with TLS
    - Lab

variables:
- name: global_architecture
  value: ${{ parameters.global_architecture }}

stages:
  - stage: Stage1
    dependsOn: []
    jobs:
    - job: Job1
      steps:
      - pwsh: |
          Write-Host "Job1"

  - stage: Stage2
    dependsOn:
      - Stage1
    jobs:
    - job: Job2
      steps:
      - pwsh: |
          Write-Host "Job2"

    - ${{ if eq(parameters.global_architecture, 'Lab') }}:
      - job: Job3
        # condition: eq(variables['global_architecture'], 'Lab')
        dependsOn:
          - Job2
        steps:
        - pwsh: |
            Write-Host "Job3"

  - stage: Stage4
    dependsOn:
      - Stage2
    jobs:
    - job: Job4
      steps:
      - pwsh: |
          Write-Host "Job4"