trigger:
  branches:
    include:
      - refs/tags/v*

pr: none

name: $(BuildID)

pool:
  vmImage: windows-2019

steps:

- pwsh: |
    ls env: | ft -autosize

- pwsh: |
    Write-Host "dasda"

- template: ../templates/template.yaml