trigger:
  branches:
    include:
      - develop
      - main
      - refs/tags/v*
  paths:
    include:
      - infra/base.tf
      - infra/base.tfvars

pr: none

name: $(BuildID)

pool:
  vmImage: windows-2019

steps:

- task: CopyFiles@2
  displayName: Copy afad-base module
  inputs:
    SourceFolder: infra
    Contents: |
     **/**.tf
     **/**.tfvars
    TargetFolder: $(Build.ArtifactStagingDirectory)/infra

- publish: '$(Build.ArtifactStagingDirectory)'
  artifact: base-dev
  displayName: Publish Artifacts

- pwsh: |
    Write-Host "##vso[build.addbuildtag]$(Build.SourceBranchName)"